<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <PackageId>WondrousTailsSolver2</PackageId>
    <AssemblyName>WondrousTailsSolver2</AssemblyName>
    <Version>3.2.2.9</Version>
    <Authors>Izzetus</Authors>
    <PackageProjectUrl>https://github.com/izzetus/EzWondrousTails2</PackageProjectUrl>
	  <CanUnloadAsync>true</CanUnloadAsync>
	  <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KamiToolKit\KamiToolKit.csproj" />
  </ItemGroup>
</Project>
